<?php

/**
 * @file
 * Contains user_tab_customizations.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function user_tab_customizations_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_tab_customizations module.
    case 'help.page.user_tab_customizations':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Customizations for the User account local tasks') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function user_tab_customizations_menu_local_tasks_alter(&$data, $route_name) {
  $alter = [
    'entity.user.canonical' => 'My Account',
    'entity.user.edit_form' => 'My Profile',
  ];

  foreach ($alter as $route => $title) {
    if (isset($data['tabs'][0][$route])) {
      $data['tabs'][0][$route]['#link']['title'] = $title;
    }
  }
}
